// Realistic dataset of 120+ Indian doctors across all medical departments
// with realistic qualifications, specializations, experience, rooms, and consultation times.

export const DOCTORS_DATA = [
  // ================= GENERAL MEDICINE (12 Doctors) =================
  {
    dept: 'GM',
    name: 'Dr. Rajesh Kumar Sharma',
    spec: 'Internal Medicine & Diabetology',
    qual: 'MBBS, MD (General Medicine)',
    exp: 18,
    room: 'Room 101',
    status: 'available',
    avgTime: 10,
    capacity: 25,
  },
  {
    dept: 'GM',
    name: 'Dr. Ananya Mukherjee',
    spec: 'Consultant Physician & Infectious Diseases',
    qual: 'MBBS, MD (Medicine), DNB',
    exp: 14,
    room: 'Room 102',
    status: 'busy',
    avgTime: 8,
    capacity: 20,
  },
  {
    dept: 'GM',
    name: 'Dr. Suresh Chandra Patnaik',
    spec: 'Geriatric Medicine & Hypertension',
    qual: 'MBBS, MD (Gen Med), FRCP',
    exp: 22,
    room: 'Room 103',
    status: 'available',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'GM',
    name: 'Dr. Meenakshi Sundaram',
    spec: 'Lifestyle Diseases & Metabolic Disorders',
    qual: 'MBBS, MD (Medicine)',
    exp: 11,
    room: 'Room 104',
    status: 'available',
    avgTime: 9,
    capacity: 22,
  },
  {
    dept: 'GM',
    name: 'Dr. Vikramaditya Rathore',
    spec: 'General Physician & Critical Care',
    qual: 'MBBS, MD (Medicine), IDCCM',
    exp: 16,
    room: 'Room 105',
    status: 'in_consultation',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'GM',
    name: 'Dr. Shalini Menon',
    spec: 'Preventive Healthcare & Adult Immunization',
    qual: 'MBBS, DNB (General Medicine)',
    exp: 9,
    room: 'Room 106',
    status: 'break',
    avgTime: 8,
    capacity: 18,
  },
  {
    dept: 'GM',
    name: 'Dr. Arvind Swaminathan',
    spec: 'Tropical Diseases & Fever Management',
    qual: 'MBBS, MD (Medicine)',
    exp: 15,
    room: 'Room 107',
    status: 'available',
    avgTime: 10,
    capacity: 25,
  },
  {
    dept: 'GM',
    name: 'Dr. Pooja Deshmukh',
    spec: 'Clinical Toxicology & Internal Medicine',
    qual: 'MBBS, MD (Gen Med)',
    exp: 8,
    room: 'Room 108',
    status: 'available',
    avgTime: 7,
    capacity: 20,
  },
  {
    dept: 'GM',
    name: 'Dr. Harish Chandra Rao',
    spec: 'Family Medicine & Chronic Care',
    qual: 'MBBS, MD (Gen Med)',
    exp: 20,
    room: 'Room 109',
    status: 'offline',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'GM',
    name: 'Dr. Deepika Senapati',
    spec: 'Adult Medicine & Rheumatic Screenings',
    qual: 'MBBS, DNB (Medicine)',
    exp: 10,
    room: 'Room 110',
    status: 'available',
    avgTime: 8,
    capacity: 22,
  },
  {
    dept: 'GM',
    name: 'Dr. Naveen Bhattacharya',
    spec: 'Comprehensive Internal Medicine',
    qual: 'MBBS, MD (Medicine)',
    exp: 13,
    room: 'Room 111',
    status: 'available',
    avgTime: 9,
    capacity: 20,
  },
  {
    dept: 'GM',
    name: 'Dr. Sunita Kulkarni',
    spec: 'General Health & Preventive Screening',
    qual: 'MBBS, MD (Medicine)',
    exp: 17,
    room: 'Room 112',
    status: 'busy',
    avgTime: 10,
    capacity: 20,
  },

  // ================= CARDIOLOGY (10 Doctors) =================
  {
    dept: 'CARD',
    name: 'Dr. Rakesh Mohanty',
    spec: 'Interventional Cardiology & Coronary Angioplasty',
    qual: 'MBBS, MD, DM (Cardiology), FACC',
    exp: 21,
    room: 'Room 201',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'CARD',
    name: 'Dr. Priya V. Nair',
    spec: 'Non-Invasive Cardiology & Echocardiography',
    qual: 'MBBS, MD (Med), DM (Cardiology)',
    exp: 15,
    room: 'Room 202',
    status: 'in_consultation',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'CARD',
    name: 'Dr. Soumya Ranjan Behera',
    spec: 'Electrophysiology & Heart Failure',
    qual: 'MBBS, MD, DM (Cardiology), FESC',
    exp: 17,
    room: 'Room 203',
    status: 'available',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'CARD',
    name: 'Dr. Tanvi Joshi',
    spec: 'Preventive Cardiology & Lipidology',
    qual: 'MBBS, MD (Gen Med), DNB (Cardiology)',
    exp: 10,
    room: 'Room 204',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'CARD',
    name: 'Dr. Amitava Ghosh',
    spec: 'Complex Coronary Interventions',
    qual: 'MBBS, MD, DM (Cardiology), FSCAI',
    exp: 24,
    room: 'Room 205',
    status: 'busy',
    avgTime: 12,
    capacity: 16,
  },
  {
    dept: 'CARD',
    name: 'Dr. Vandana Singhania',
    spec: 'Pediatric Cardiology & Congenital Heart Defects',
    qual: 'MBBS, MD (Peds), DM (Cardiology)',
    exp: 14,
    room: 'Room 206',
    status: 'available',
    avgTime: 14,
    capacity: 15,
  },
  {
    dept: 'CARD',
    name: 'Dr. Pradeep Kumar Das',
    spec: 'Cardiac Rehabilitation & Heart Rhythm Disorders',
    qual: 'MBBS, MD (Medicine), PGDCC',
    exp: 12,
    room: 'Room 207',
    status: 'break',
    avgTime: 9,
    capacity: 18,
  },
  {
    dept: 'CARD',
    name: 'Dr. Sneha Reddy',
    spec: 'Women Heart Health & Vascular Medicine',
    qual: 'MBBS, MD, DM (Cardiology)',
    exp: 11,
    room: 'Room 208',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'CARD',
    name: 'Dr. Manoj Tripathy',
    spec: 'Structural Heart Disease & TAVR',
    qual: 'MBBS, MD, DM (Cardiology)',
    exp: 19,
    room: 'Room 209',
    status: 'available',
    avgTime: 12,
    capacity: 16,
  },
  {
    dept: 'CARD',
    name: 'Dr. Alok Nath Panda',
    spec: 'Clinical Cardiology & Stress Testing',
    qual: 'MBBS, MD (Medicine), Dip Cardio',
    exp: 8,
    room: 'Room 210',
    status: 'offline',
    avgTime: 8,
    capacity: 22,
  },

  // ================= DERMATOLOGY (8 Doctors) =================
  {
    dept: 'DERM',
    name: 'Dr. Lipika Sahoo',
    spec: 'Clinical Dermatology & Cosmetology',
    qual: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    exp: 14,
    room: 'Room 121',
    status: 'available',
    avgTime: 8,
    capacity: 25,
  },
  {
    dept: 'DERM',
    name: 'Dr. Rohan Bhattacharya',
    spec: 'Trichology & Hair Restoration',
    qual: 'MBBS, DVD, DNB (Dermatology)',
    exp: 11,
    room: 'Room 122',
    status: 'available',
    avgTime: 8,
    capacity: 22,
  },
  {
    dept: 'DERM',
    name: 'Dr. Swati Mishra',
    spec: 'Pediatric Dermatology & Eczema Care',
    qual: 'MBBS, MD (DVL)',
    exp: 9,
    room: 'Room 123',
    status: 'in_consultation',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'DERM',
    name: 'Dr. Kshitij Saxena',
    spec: 'Laser Surgery & Dermatosurgery',
    qual: 'MBBS, MD (Skin & VD), FAM',
    exp: 16,
    room: 'Room 124',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'DERM',
    name: 'Dr. Rashmi Rekha Jena',
    spec: 'Psoriasis & Autoimmune Bullous Disorders',
    qual: 'MBBS, MD (Dermatology)',
    exp: 13,
    room: 'Room 125',
    status: 'busy',
    avgTime: 9,
    capacity: 20,
  },
  {
    dept: 'DERM',
    name: 'Dr. Abhishek Roy',
    spec: 'Aesthetic Medicine & Anti-Aging',
    qual: 'MBBS, DDVL',
    exp: 7,
    room: 'Room 126',
    status: 'available',
    avgTime: 7,
    capacity: 25,
  },
  {
    dept: 'DERM',
    name: 'Dr. Neha Agarwal',
    spec: 'Allergy & Contact Dermatitis',
    qual: 'MBBS, MD (DVL)',
    exp: 10,
    room: 'Room 127',
    status: 'break',
    avgTime: 8,
    capacity: 20,
  },
  {
    dept: 'DERM',
    name: 'Dr. Bimalendu Sen',
    spec: 'General Skin Consultation & Infections',
    qual: 'MBBS, DVD',
    exp: 18,
    room: 'Room 128',
    status: 'available',
    avgTime: 7,
    capacity: 25,
  },

  // ================= PEDIATRICS (10 Doctors) =================
  {
    dept: 'PEDS',
    name: 'Dr. Manas Ranjan Tripathy',
    spec: 'General Pediatrics & Newborn Care',
    qual: 'MBBS, MD (Pediatrics), FIAP',
    exp: 19,
    room: 'Room 211',
    status: 'available',
    avgTime: 10,
    capacity: 24,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Shweta Bharadwaj',
    spec: 'Neonatology & Child Nutrition',
    qual: 'MBBS, MD (Pediatrics), DM (Neonatology)',
    exp: 13,
    room: 'Room 212',
    status: 'available',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Debabrata Swain',
    spec: 'Pediatric Pulmonology & Allergy',
    qual: 'MBBS, DNB (Pediatrics)',
    exp: 11,
    room: 'Room 213',
    status: 'busy',
    avgTime: 9,
    capacity: 22,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Ritu Choudhury',
    spec: 'Developmental Pediatrics & Behavioral Care',
    qual: 'MBBS, MD (Pediatrics)',
    exp: 15,
    room: 'Room 214',
    status: 'in_consultation',
    avgTime: 15,
    capacity: 16,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Karthik Sundararajan',
    spec: 'Pediatric Infectious Diseases',
    qual: 'MBBS, MD (Pediatrics), FPID',
    exp: 12,
    room: 'Room 215',
    status: 'available',
    avgTime: 9,
    capacity: 22,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Sanghamitra Panda',
    spec: 'Immunization & Well-Baby Clinic',
    qual: 'MBBS, DCH, DNB (Pediatrics)',
    exp: 17,
    room: 'Room 216',
    status: 'available',
    avgTime: 8,
    capacity: 25,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Chirag Dave',
    spec: 'Pediatric Nephrology',
    qual: 'MBBS, MD (Peds), FPN',
    exp: 10,
    room: 'Room 217',
    status: 'break',
    avgTime: 11,
    capacity: 18,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Madhusmita Kar',
    spec: 'Adolescent Medicine & Growth Disorders',
    qual: 'MBBS, MD (Pediatrics)',
    exp: 8,
    room: 'Room 218',
    status: 'available',
    avgTime: 9,
    capacity: 20,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Ajay Verma',
    spec: 'Pediatric Intensive Care & Emergency',
    qual: 'MBBS, MD (Peds), IFPCC',
    exp: 14,
    room: 'Room 219',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'PEDS',
    name: 'Dr. Sunayana Hegde',
    spec: 'General Pediatric OPD',
    qual: 'MBBS, DCH',
    exp: 6,
    room: 'Room 220',
    status: 'offline',
    avgTime: 8,
    capacity: 24,
  },

  // ================= ORTHOPEDICS (10 Doctors) =================
  {
    dept: 'ORTHO',
    name: 'Dr. Nihar Ranjan Panda',
    spec: 'Joint Replacement & Arthroplasty (Knee & Hip)',
    qual: 'MBBS, MS (Orthopedics), MCh (Ortho)',
    exp: 23,
    room: 'Room 301',
    status: 'available',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Kalyan Kumar Jena',
    spec: 'Trauma & Complex Fracture Reconstruction',
    qual: 'MBBS, MS (Orthopedics), AO Trauma Fellow',
    exp: 16,
    room: 'Room 302',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Siddharth Vardhan',
    spec: 'Spine Surgery & Scoliosis Correction',
    qual: 'MBBS, MS (Ortho), FNB (Spine Surgery)',
    exp: 14,
    room: 'Room 303',
    status: 'in_consultation',
    avgTime: 15,
    capacity: 16,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Archana Mohapatra',
    spec: 'Pediatric Orthopedics & Deformity Correction',
    qual: 'MBBS, MS (Orthopedics)',
    exp: 12,
    room: 'Room 304',
    status: 'available',
    avgTime: 11,
    capacity: 18,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Gautam Venkatesh',
    spec: 'Arthroscopy & Sports Medicine (Shoulder & Knee)',
    qual: 'MBBS, DNB (Ortho), Fellowship Sports Med',
    exp: 13,
    room: 'Room 305',
    status: 'busy',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Bibhu Prasad Rout',
    spec: 'Hand, Wrist & Reconstructive Microsurgery',
    qual: 'MBBS, MS (Orthopedics)',
    exp: 18,
    room: 'Room 306',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Tarun Kapur',
    spec: 'Foot & Ankle Surgery',
    qual: 'MBBS, D.Ortho, DNB (Orthopedics)',
    exp: 9,
    room: 'Room 307',
    status: 'break',
    avgTime: 9,
    capacity: 20,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Sourav Samantaray',
    spec: 'Musculoskeletal Oncology & Bone Tumors',
    qual: 'MBBS, MS (Ortho), FIMS',
    exp: 11,
    room: 'Room 308',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Vinay Mohan Joshi',
    spec: 'Geriatric Orthopedics & Osteoporosis Care',
    qual: 'MBBS, MS (Orthopedics)',
    exp: 20,
    room: 'Room 309',
    status: 'available',
    avgTime: 9,
    capacity: 24,
  },
  {
    dept: 'ORTHO',
    name: 'Dr. Jagdish Chandra Pradhan',
    spec: 'General Orthopedic Consultation',
    qual: 'MBBS, D.Ortho',
    exp: 15,
    room: 'Room 310',
    status: 'offline',
    avgTime: 8,
    capacity: 22,
  },

  // ================= NEUROLOGY (8 Doctors) =================
  {
    dept: 'NEURO',
    name: 'Dr. Bhabani Shankar Pati',
    spec: 'Stroke Management & Interventional Neurology',
    qual: 'MBBS, MD (Medicine), DM (Neurology)',
    exp: 20,
    room: 'Room 311',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Shalini S. Nambiar',
    spec: 'Epilepsy & Neuro-Electrophysiology',
    qual: 'MBBS, MD (Med), DM (Neuro), PDF (Epilepsy)',
    exp: 15,
    room: 'Room 312',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Ashok Kumar Mahapatra',
    spec: 'Movement Disorders & Parkinson Disease Care',
    qual: 'MBBS, MD, DM (Neurology), FINR',
    exp: 26,
    room: 'Room 313',
    status: 'in_consultation',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Preeti Vasudevan',
    spec: 'Demyelinating Disorders & Multiple Sclerosis',
    qual: 'MBBS, MD (Gen Med), DNB (Neurology)',
    exp: 11,
    room: 'Room 314',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Debasis Acharya',
    spec: 'Headache Medicine & Neuromuscular Disorders',
    qual: 'MBBS, MD, DM (Neurology)',
    exp: 13,
    room: 'Room 315',
    status: 'busy',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Anupama Srinivasan',
    spec: 'Cognitive Neurology & Dementia Care',
    qual: 'MBBS, MD, DM (Neurology)',
    exp: 9,
    room: 'Room 316',
    status: 'available',
    avgTime: 14,
    capacity: 15,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Somnath Bhattacharya',
    spec: 'Pediatric Neurology',
    qual: 'MBBS, MD (Peds), DM (Neurology)',
    exp: 16,
    room: 'Room 317',
    status: 'break',
    avgTime: 12,
    capacity: 16,
  },
  {
    dept: 'NEURO',
    name: 'Dr. Prashant K. Mishra',
    spec: 'Clinical Neurophysiology (EMG/NCV/EEG)',
    qual: 'MBBS, MD (Medicine), DNB (Neurology)',
    exp: 10,
    room: 'Room 318',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },

  // ================= ENT / OTORHINOLARYNGOLOGY (8 Doctors) =================
  {
    dept: 'ENT',
    name: 'Dr. Jyoti Ranjan Rath',
    spec: 'Endoscopic Sinus & Skull Base Surgery',
    qual: 'MBBS, MS (ENT), DNB (Otorhinolaryngology)',
    exp: 18,
    room: 'Room 131',
    status: 'available',
    avgTime: 9,
    capacity: 22,
  },
  {
    dept: 'ENT',
    name: 'Dr. Shruti Somani',
    spec: 'Otology, Cochlear Implantation & Vertigo',
    qual: 'MBBS, MS (ENT), Fellowship Otology',
    exp: 14,
    room: 'Room 132',
    status: 'available',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'ENT',
    name: 'Dr. Chinmayee Mohanty',
    spec: 'Laryngology, Voice Disorders & Swallowing Care',
    qual: 'MBBS, MS (ENT)',
    exp: 10,
    room: 'Room 133',
    status: 'busy',
    avgTime: 8,
    capacity: 24,
  },
  {
    dept: 'ENT',
    name: 'Dr. Sameer Quadri',
    spec: 'Head & Neck Oncologic Surgery',
    qual: 'MBBS, MS (ENT), MCh (Head & Neck)',
    exp: 16,
    room: 'Room 134',
    status: 'in_consultation',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'ENT',
    name: 'Dr. Tapas Kumar Swain',
    spec: 'Pediatric ENT & Sleep Apnea Surgery',
    qual: 'MBBS, DLO, DNB (ENT)',
    exp: 12,
    room: 'Room 135',
    status: 'available',
    avgTime: 8,
    capacity: 24,
  },
  {
    dept: 'ENT',
    name: 'Dr. Divya Ramesh',
    spec: 'Rhinoplasty & Facial Plastics',
    qual: 'MBBS, MS (ENT)',
    exp: 8,
    room: 'Room 136',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'ENT',
    name: 'Dr. Braja Sundar Srichandan',
    spec: 'General ENT & Allergy Desensitization',
    qual: 'MBBS, MS (ENT)',
    exp: 21,
    room: 'Room 137',
    status: 'break',
    avgTime: 8,
    capacity: 22,
  },
  {
    dept: 'ENT',
    name: 'Dr. Niloufer Khan',
    spec: 'Tinnitus & Balance Disorders Clinic',
    qual: 'MBBS, DLO',
    exp: 7,
    room: 'Room 138',
    status: 'available',
    avgTime: 8,
    capacity: 25,
  },

  // ================= OPHTHALMOLOGY (8 Doctors) =================
  {
    dept: 'OPHT',
    name: 'Dr. Subhashree Sen',
    spec: 'Cataract, Phacoemulsification & Refractive Surgery',
    qual: 'MBBS, MS (Ophthalmology), FICO (UK)',
    exp: 17,
    room: 'Room 141',
    status: 'available',
    avgTime: 8,
    capacity: 25,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Hemant Kumar Sahu',
    spec: 'Vitreoretinal Diseases & Diabetic Retinopathy',
    qual: 'MBBS, MS (Ophthalmology), FVRS',
    exp: 15,
    room: 'Room 142',
    status: 'available',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Kalyani Balakrishnan',
    spec: 'Glaucoma & Anterior Segment Disorders',
    qual: 'MBBS, MS (Ophthal), DNB',
    exp: 13,
    room: 'Room 143',
    status: 'in_consultation',
    avgTime: 9,
    capacity: 22,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Amitav Tripathy',
    spec: 'Cornea, Ocular Surface & Keratoplasty',
    qual: 'MBBS, MS (Ophthal), Cornea Fellow',
    exp: 12,
    room: 'Room 144',
    status: 'busy',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Pallavi Varma',
    spec: 'Pediatric Ophthalmology & Squint Strabismus',
    qual: 'MBBS, DO, DNB (Ophthalmology)',
    exp: 10,
    room: 'Room 145',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Srikant Mohapatra',
    spec: 'Oculoplastics & Orbit Surgery',
    qual: 'MBBS, MS (Ophthalmology)',
    exp: 14,
    room: 'Room 146',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Ruchi Singhal',
    spec: 'Uveitis & Ocular Immunology',
    qual: 'MBBS, MS (Ophthal)',
    exp: 9,
    room: 'Room 147',
    status: 'break',
    avgTime: 9,
    capacity: 22,
  },
  {
    dept: 'OPHT',
    name: 'Dr. Binod Bihari Mishra',
    spec: 'Comprehensive Eye Examination & Vision Care',
    qual: 'MBBS, DO',
    exp: 22,
    room: 'Room 148',
    status: 'available',
    avgTime: 7,
    capacity: 30,
  },

  // ================= DENTISTRY (6 Doctors) =================
  {
    dept: 'DENT',
    name: 'Dr. Aravind Menon',
    spec: 'Oral & Maxillofacial Surgery',
    qual: 'BDS, MDS (Oral & Maxillofacial Surgery)',
    exp: 15,
    room: 'Dental Suite 1',
    status: 'available',
    avgTime: 15,
    capacity: 18,
  },
  {
    dept: 'DENT',
    name: 'Dr. Smruti Snigdha Das',
    spec: 'Conservative Dentistry & Endodontics (Root Canal)',
    qual: 'BDS, MDS (Endodontics)',
    exp: 12,
    room: 'Dental Suite 2',
    status: 'available',
    avgTime: 15,
    capacity: 18,
  },
  {
    dept: 'DENT',
    name: 'Dr. Gaurav Chhabra',
    spec: 'Orthodontics & Dentofacial Orthopedics (Braces)',
    qual: 'BDS, MDS (Orthodontics), MOrth RCSEd',
    exp: 13,
    room: 'Dental Suite 3',
    status: 'in_consultation',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'DENT',
    name: 'Dr. Prachi Srivastava',
    spec: 'Periodontics & Dental Implantology',
    qual: 'BDS, MDS (Periodontics)',
    exp: 10,
    room: 'Dental Suite 4',
    status: 'available',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'DENT',
    name: 'Dr. Nityananda Pradhan',
    spec: 'Prosthodontics, Crown & Bridge',
    qual: 'BDS, MDS (Prosthodontics)',
    exp: 17,
    room: 'Dental Suite 5',
    status: 'busy',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'DENT',
    name: 'Dr. Jayashree Nayak',
    spec: 'Pediatric Dentistry & Preventive Oral Care',
    qual: 'BDS, MDS (Pedodontics)',
    exp: 8,
    room: 'Dental Suite 6',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },

  // ================= GYNECOLOGY & OBSTETRICS (10 Doctors) =================
  {
    dept: 'GYN',
    name: 'Dr. Sandhya Rani Mohanty',
    spec: 'High-Risk Pregnancy & Fetal Medicine',
    qual: 'MBBS, MD (Obstetrics & Gynecology), FICOG',
    exp: 22,
    room: 'Room 221',
    status: 'available',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'GYN',
    name: 'Dr. Malabika Pattnaik',
    spec: 'Laparoscopic Gynecologic Surgery & Infertility',
    qual: 'MBBS, MS (OBG), FMAS, DRM (Germany)',
    exp: 18,
    room: 'Room 222',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'GYN',
    name: 'Dr. Nandini Sengupta',
    spec: 'Gynecological Oncology & Preventive Screening',
    qual: 'MBBS, MD (OBG), Fellowship Gynae Oncology',
    exp: 15,
    room: 'Room 223',
    status: 'in_consultation',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'GYN',
    name: 'Dr. Rekha Sundaram',
    spec: 'Adolescent Gynecology & PCOS Management',
    qual: 'MBBS, DGO, DNB (OBG)',
    exp: 12,
    room: 'Room 224',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'GYN',
    name: 'Dr. Suchitra Kumari Kar',
    spec: 'Urogynecology & Pelvic Floor Disorders',
    qual: 'MBBS, MS (Obstetrics & Gynecology)',
    exp: 16,
    room: 'Room 225',
    status: 'busy',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'GYN',
    name: 'Dr. Archana K. Pillai',
    spec: 'Reproductive Endocrinology & IVF',
    qual: 'MBBS, MD (OBG), Fellowship ART',
    exp: 11,
    room: 'Room 226',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'GYN',
    name: 'Dr. Jayanti Rath',
    spec: 'Menopause Clinic & Hormonal Health',
    qual: 'MBBS, MD (OBG)',
    exp: 20,
    room: 'Room 227',
    status: 'break',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'GYN',
    name: 'Dr. Anamika Tyagi',
    spec: 'Obstetric Ultrasound & Prenatal Care',
    qual: 'MBBS, MS (OBG), Dip Fetal Med',
    exp: 9,
    room: 'Room 228',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'GYN',
    name: 'Dr. Manorama Swain',
    spec: 'General Antenatal & Postnatal Care',
    qual: 'MBBS, DGO',
    exp: 25,
    room: 'Room 229',
    status: 'available',
    avgTime: 9,
    capacity: 25,
  },
  {
    dept: 'GYN',
    name: 'Dr. Shilpi Agarwal',
    spec: 'Maternal-Fetal Consultation',
    qual: 'MBBS, MS (OBG)',
    exp: 7,
    room: 'Room 230',
    status: 'offline',
    avgTime: 9,
    capacity: 20,
  },

  // ================= PSYCHIATRY (6 Doctors) =================
  {
    dept: 'PSYCH',
    name: 'Dr. Pradipta Kumar Mishra',
    spec: 'Adult Psychiatry, Depression & Anxiety Disorders',
    qual: 'MBBS, MD (Psychiatry), FIPS',
    exp: 19,
    room: 'Room 321',
    status: 'available',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'PSYCH',
    name: 'Dr. Shobha Subramanian',
    spec: 'Child & Adolescent Behavioral Psychiatry',
    qual: 'MBBS, DPM, DNB (Psychiatry)',
    exp: 14,
    room: 'Room 322',
    status: 'available',
    avgTime: 18,
    capacity: 14,
  },
  {
    dept: 'PSYCH',
    name: 'Dr. Debasis Panigrahi',
    spec: 'Addiction Medicine & De-Addiction Counseling',
    qual: 'MBBS, MD (Psychiatry)',
    exp: 16,
    room: 'Room 323',
    status: 'in_consultation',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'PSYCH',
    name: 'Dr. Tanya Bharadwaj',
    spec: 'Neuropsychiatry, Sleep & Stress Disorders',
    qual: 'MBBS, MD (Psychiatry)',
    exp: 10,
    room: 'Room 324',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'PSYCH',
    name: 'Dr. Soumya Kanti Bose',
    spec: 'Geriatric Psychiatry & Cognitive Disorders',
    qual: 'MBBS, MD (Psychiatry)',
    exp: 12,
    room: 'Room 325',
    status: 'busy',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'PSYCH',
    name: 'Dr. Niharika Senapati',
    spec: 'Psychotherapy & Mood Disorders',
    qual: 'MBBS, DPM',
    exp: 8,
    room: 'Room 326',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },

  // ================= GASTROENTEROLOGY (6 Doctors) =================
  {
    dept: 'GASTRO',
    name: 'Dr. Subhash Chandra Panda',
    spec: 'Medical Gastroenterology & Diagnostic Endoscopy',
    qual: 'MBBS, MD (Med), DM (Gastroenterology)',
    exp: 21,
    room: 'Room 331',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'GASTRO',
    name: 'Dr. Vivek Shankaran',
    spec: 'Hepatology, Cirrhosis & Liver Transplant Medicine',
    qual: 'MBBS, MD, DM (Hepatology), FACG',
    exp: 16,
    room: 'Room 332',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'GASTRO',
    name: 'Dr. Minakshi Satapathy',
    spec: 'Therapeutic Endoscopy & ERCP',
    qual: 'MBBS, MD, DM (Gastroenterology)',
    exp: 13,
    room: 'Room 333',
    status: 'in_consultation',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'GASTRO',
    name: 'Dr. Anurag Dixit',
    spec: 'Inflammatory Bowel Disease (IBD & Crohn)',
    qual: 'MBBS, MD (Gen Med), DNB (Gastroenterology)',
    exp: 11,
    room: 'Room 334',
    status: 'busy',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'GASTRO',
    name: 'Dr. Rakesh Ranjan Swain',
    spec: 'GI Motility, Acid Peptic Disease & IBS',
    qual: 'MBBS, MD, DM (Gastroenterology)',
    exp: 15,
    room: 'Room 335',
    status: 'available',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'GASTRO',
    name: 'Dr. Kalyani Iyer',
    spec: 'Pancreato-Biliary Disorders',
    qual: 'MBBS, MD (Med), DM (Gastro)',
    exp: 9,
    room: 'Room 336',
    status: 'break',
    avgTime: 11,
    capacity: 18,
  },

  // ================= UROLOGY (6 Doctors) =================
  {
    dept: 'UROL',
    name: 'Dr. Bijayananda Mohapatra',
    spec: 'Endourology, Kidney Stones & Laser Surgery',
    qual: 'MBBS, MS (Gen Surg), MCh (Urology)',
    exp: 22,
    room: 'Room 341',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'UROL',
    name: 'Dr. Siddharth Mathur',
    spec: 'Uro-Oncology & Robotic Prostate Surgery',
    qual: 'MBBS, MS, MCh (Uro), DNB (Urology)',
    exp: 16,
    room: 'Room 342',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'UROL',
    name: 'Dr. Amrita Mukherjee',
    spec: 'Female Urology & Urinary Incontinence',
    qual: 'MBBS, MS (Surg), MCh (Urology)',
    exp: 12,
    room: 'Room 343',
    status: 'in_consultation',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'UROL',
    name: 'Dr. Debabrata Pradhan',
    spec: 'Andrology, Male Infertility & Sexual Health',
    qual: 'MBBS, MS (Surgery), MCh (Urology)',
    exp: 14,
    room: 'Room 344',
    status: 'busy',
    avgTime: 10,
    capacity: 20,
  },
  {
    dept: 'UROL',
    name: 'Dr. Varun Venkatesan',
    spec: 'Reconstructive Urology & Urethral Strictures',
    qual: 'MBBS, MS, MCh (Urology)',
    exp: 10,
    room: 'Room 345',
    status: 'available',
    avgTime: 11,
    capacity: 18,
  },
  {
    dept: 'UROL',
    name: 'Dr. Sanjay Panda',
    spec: 'Pediatric Urology & Congenital Anomalies',
    qual: 'MBBS, MS (Surgery), DNB (Urology)',
    exp: 13,
    room: 'Room 346',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },

  // ================= PULMONOLOGY (6 Doctors) =================
  {
    dept: 'PULM',
    name: 'Dr. Manoranjan Dash',
    spec: 'Interventional Pulmonology, Bronchoscopy & EBUS',
    qual: 'MBBS, MD (Pulmonary Medicine), FACP',
    exp: 19,
    room: 'Room 351',
    status: 'available',
    avgTime: 12,
    capacity: 20,
  },
  {
    dept: 'PULM',
    name: 'Dr. Meera Chandrasekhar',
    spec: 'Asthma, COPD & Allergic Airway Diseases',
    qual: 'MBBS, MD (Respiratory Med), DTCD',
    exp: 15,
    room: 'Room 352',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'PULM',
    name: 'Dr. Alok Kumar Behera',
    spec: 'Sleep Medicine & Sleep Apnea (Polysomnography)',
    qual: 'MBBS, MD (TB & Chest), DNB',
    exp: 13,
    room: 'Room 353',
    status: 'in_consultation',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'PULM',
    name: 'Dr. Rituja Deshpande',
    spec: 'Interstitial Lung Diseases (ILD) & Sarcoidosis',
    qual: 'MBBS, MD (Pulmonology)',
    exp: 11,
    room: 'Room 354',
    status: 'busy',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'PULM',
    name: 'Dr. Prakash Chandra Jena',
    spec: 'Tuberculosis & Post-COVID Respiratory Care',
    qual: 'MBBS, DTCD, MD (Chest)',
    exp: 22,
    room: 'Room 355',
    status: 'available',
    avgTime: 9,
    capacity: 24,
  },
  {
    dept: 'PULM',
    name: 'Dr. Anupama Nair',
    spec: 'Critical Care & Pulmonary Rehabilitation',
    qual: 'MBBS, DNB (Respiratory Medicine)',
    exp: 8,
    room: 'Room 356',
    status: 'break',
    avgTime: 10,
    capacity: 20,
  },

  // ================= ENDOCRINOLOGY (6 Doctors) =================
  {
    dept: 'ENDO',
    name: 'Dr. Kishore Kumar Tripathy',
    spec: 'Advanced Diabetology & Thyroid Disorders',
    qual: 'MBBS, MD (Medicine), DM (Endocrinology)',
    exp: 20,
    room: 'Room 361',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'ENDO',
    name: 'Dr. Aparna K. Sundaram',
    spec: 'Pediatric Endocrinology & Growth Hormone Care',
    qual: 'MBBS, MD (Peds), DM (Endocrinology)',
    exp: 14,
    room: 'Room 362',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'ENDO',
    name: 'Dr. Biswajit Sahoo',
    spec: 'Pituitary & Adrenal Disorders, Osteoporosis',
    qual: 'MBBS, MD, DM (Endocrinology)',
    exp: 12,
    room: 'Room 363',
    status: 'in_consultation',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'ENDO',
    name: 'Dr. Gayatri Joshi',
    spec: 'Obesity, Metabolic Syndrome & PCOS',
    qual: 'MBBS, DNB (Medicine), DNB (Endocrinology)',
    exp: 10,
    room: 'Room 364',
    status: 'available',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'ENDO',
    name: 'Dr. Sarthak Mohanty',
    spec: 'Gestational Diabetes & Endocrine Hypertension',
    qual: 'MBBS, MD (Gen Med), Dip Endo',
    exp: 8,
    room: 'Room 365',
    status: 'busy',
    avgTime: 9,
    capacity: 24,
  },
  {
    dept: 'ENDO',
    name: 'Dr. Sunanda Mukherjee',
    spec: 'General Endocrine & Calcium Metabolism',
    qual: 'MBBS, MD (Medicine)',
    exp: 16,
    room: 'Room 366',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },

  // ================= ONCOLOGY (6 Doctors) =================
  {
    dept: 'ONCO',
    name: 'Dr. Soumen Roy Choudhury',
    spec: 'Medical Oncology & Targeted Chemotherapy',
    qual: 'MBBS, MD (Medicine), DM (Medical Oncology)',
    exp: 18,
    room: 'Room 371',
    status: 'available',
    avgTime: 15,
    capacity: 16,
  },
  {
    dept: 'ONCO',
    name: 'Dr. Suchismita Nayak',
    spec: 'Radiation Oncology, IGRT & Brachytherapy',
    qual: 'MBBS, MD (Radiation Oncology), DNB',
    exp: 15,
    room: 'Room 372',
    status: 'available',
    avgTime: 14,
    capacity: 16,
  },
  {
    dept: 'ONCO',
    name: 'Dr. Deepak Kumar Verma',
    spec: 'Surgical Oncology, Breast & GI Malignancies',
    qual: 'MBBS, MS (Surgery), MCh (Surgical Oncology)',
    exp: 17,
    room: 'Room 373',
    status: 'in_consultation',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'ONCO',
    name: 'Dr. Purnima Venkataraman',
    spec: 'Hematologic Oncology & Leukemia Care',
    qual: 'MBBS, MD, DM (Clinical Hematology)',
    exp: 12,
    room: 'Room 374',
    status: 'busy',
    avgTime: 15,
    capacity: 15,
  },
  {
    dept: 'ONCO',
    name: 'Dr. Hemant K. Patnaik',
    spec: 'Head & Neck Oncology',
    qual: 'MBBS, MS, MCh (Surgical Oncology)',
    exp: 14,
    room: 'Room 375',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'ONCO',
    name: 'Dr. Ananya Ray',
    spec: 'Cancer Screening & Preventive Oncology',
    qual: 'MBBS, MD (Radiotherapy)',
    exp: 9,
    room: 'Room 376',
    status: 'break',
    avgTime: 10,
    capacity: 20,
  },

  // ================= GENERAL SURGERY (8 Doctors) =================
  {
    dept: 'SURG',
    name: 'Dr. Debi Prasad Mohanty',
    spec: 'Advanced Laparoscopic & GI Surgery',
    qual: 'MBBS, MS (General Surgery), FMAS, FIAGES',
    exp: 22,
    room: 'Room 381',
    status: 'available',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'SURG',
    name: 'Dr. Kavitha S. Narayanan',
    spec: 'Breast Surgery & Endocrine Surgery (Thyroid)',
    qual: 'MBBS, MS (General Surgery), DNB',
    exp: 16,
    room: 'Room 382',
    status: 'available',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'SURG',
    name: 'Dr. Trilochan Swain',
    spec: 'Hernia Repair & Abdominal Wall Reconstruction',
    qual: 'MBBS, MS (General Surgery), FICS',
    exp: 19,
    room: 'Room 383',
    status: 'in_consultation',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'SURG',
    name: 'Dr. Rahul Singhal',
    spec: 'Proctology & Laser Anorectal Surgery',
    qual: 'MBBS, MS (Surgery), FAIS',
    exp: 12,
    room: 'Room 384',
    status: 'busy',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'SURG',
    name: 'Dr. Sasmita Panigrahi',
    spec: 'Diabetic Foot Surgery & Wound Management',
    qual: 'MBBS, MS (General Surgery)',
    exp: 14,
    room: 'Room 385',
    status: 'available',
    avgTime: 11,
    capacity: 20,
  },
  {
    dept: 'SURG',
    name: 'Dr. Abhinav Mukherjee',
    spec: 'Emergency & Trauma Surgery',
    qual: 'MBBS, MS (General Surgery)',
    exp: 10,
    room: 'Room 386',
    status: 'available',
    avgTime: 10,
    capacity: 22,
  },
  {
    dept: 'SURG',
    name: 'Dr. Bhaskar Rao',
    spec: 'Minimal Access & Bariatric Surgery',
    qual: 'MBBS, MS, FALS (Bariatric)',
    exp: 15,
    room: 'Room 387',
    status: 'break',
    avgTime: 12,
    capacity: 18,
  },
  {
    dept: 'SURG',
    name: 'Dr. Niranjan Mishra',
    spec: 'General Surgical OPD & Day Care Procedures',
    qual: 'MBBS, MS (General Surgery)',
    exp: 25,
    room: 'Room 388',
    status: 'available',
    avgTime: 9,
    capacity: 25,
  },

  // ================= EMERGENCY MEDICINE (4 Doctors) =================
  {
    dept: 'EMER',
    name: 'Dr. Sourav Nayak',
    spec: 'Emergency Medicine & Trauma Resuscitation',
    qual: 'MBBS, MD (Emergency Medicine), MEM',
    exp: 14,
    room: 'Emergency Triage',
    status: 'available',
    avgTime: 8,
    capacity: 30,
  },
  {
    dept: 'EMER',
    name: 'Dr. Pooja Balaji',
    spec: 'Critical Care & Pediatric Emergency',
    qual: 'MBBS, DNB (Emergency Medicine)',
    exp: 10,
    room: 'Emergency Red Bay',
    status: 'available',
    avgTime: 8,
    capacity: 30,
  },
  {
    dept: 'EMER',
    name: 'Dr. Rakesh Tripathy',
    spec: 'Acute Cardiac & Stroke Care',
    qual: 'MBBS, MD (Emergency Med), FACEE',
    exp: 12,
    room: 'Emergency Yellow Bay',
    status: 'busy',
    avgTime: 8,
    capacity: 30,
  },
  {
    dept: 'EMER',
    name: 'Dr. Anwesha Ghosh',
    spec: 'Emergency Ultrasound & Acute Medicine',
    qual: 'MBBS, MEM',
    exp: 7,
    room: 'Emergency Observation',
    status: 'available',
    avgTime: 8,
    capacity: 30,
  },
];
