// Synthetic demo reviews for KIMS Queue.
// Each entry: [ reviewerType, rating, comment, category, request, deptCode, areaCode, reviewerName ]
// These are DEMO records (is_demo=1) and must NEVER be presented as verified real testimonials.
export const REVIEW_DATA = [
  ['PATIENT', 5, 'Getting a token online is much simpler than queuing at the counter. The live queue made it easy to plan when to come back.', 'QUEUE_TRACKING', null, 'GM', 'GM-OPD', 'Anita Mohanty'],
  ['PATIENT', 5, 'From choosing my department to receiving the token took under a minute. Very convenient.', 'TOKEN_GENERATION', null, 'CARD', 'CARD-OPD', 'Rakesh Patnaik'],
  ['PATIENT', 5, 'The interface is clear and the token details were accurate. It would help if the estimated wait updated more often.', 'WAIT_TIME', 'Refresh estimated wait time more frequently.', 'ORTHO', 'ORTHO-OPD', 'Sneha Das'],
  ['PATIENT', 5, 'I could step away and watch my position from my phone. Really reduced the waiting-area stress.', 'QUEUE_TRACKING', null, 'PEDS', 'PEDS-OPD', 'Priya Sahoo'],
  ['PATIENT', 5, 'Simple to use and clearly laid out. I would like an alert a few tokens before my turn.', 'NOTIFICATIONS', 'Add a near-turn notification when 2-3 people are ahead.', 'NEURO', 'NEURO-OPD', 'Bibhu Rout'],
  ['PATIENT', 3, 'Queue tracking worked, but I was unsure which service area to select. A short description under each service would help.', 'SERVICE_INFORMATION', 'Add short descriptions under each service area.', 'DERM', 'DERM-OPD', 'Deepa Nanda'],
  ['PATIENT', 5, 'The mobile page is neat and the token number is the first thing I see. Great.', 'MOBILE_EXPERIENCE', null, 'ENT', 'ENT-OPD', 'Sourav Jena'],
  ['PATIENT', 2, 'Useful idea, but my queue position did not update right away. Real-time updates would make it far more reliable.', 'QUEUE_TRACKING', 'Improve real-time queue position updates.', 'RAD', 'RAD-CT', 'Mamta Panda'],
  ['PATIENT', 4, 'Booking was quick and the notifications helped. Sometimes the app felt slow on my older phone.', 'PERFORMANCE', 'Improve loading speed on low-end devices.', 'PHARM', 'PHARM-OP', 'Gopal Swain'],
  ['PATIENT', 5, 'Love that I can get a token without standing in line and still track my turn.', 'TOKEN_GENERATION', null, 'BILL', 'BILL-COUNTER', 'Rina Mishra'],
  ['PATIENT', 5, 'The live board is very helpful. I would like it to also show the expected wait per counter.', 'WAIT_TIME', 'Show per-counter expected wait on the live board.', 'CARD', 'CARD-ECG', 'Lipi Senapati'],
  ['PATIENT', 5, 'Emergency help is easy to find, which is reassuring during a hospital visit.', 'EMERGENCY_HELP', null, 'OPD', 'OPD-REG', 'Nikhil Tripathy'],
  ['PATIENT', 4, 'Mostly smooth, but a Hindi/Odia option would help older patients use it independently.', 'ACCESSIBILITY', 'Add multilingual UI (Hindi/Odia).', 'GM', 'GM-FUP', 'Suchitra Kar'],
  ['PATIENT', 5, 'The token system saved me from standing around for nearly an hour.', 'QUEUE_TRACKING', null, 'ORTHO', 'ORTHO-FX', 'Arun Behera'],
  ['PATIENT', 5, 'Very easy interface. Got my lab token in seconds and the counter name was clear.', 'TOKEN_GENERATION', null, 'PATH', 'PATH-SAMP', 'Deepa Nanda'],
  ['PATIENT', 4, 'Notifications are handy. I would like them when my turn is close, not just when it is called.', 'NOTIFICATIONS', 'Notify me a couple of tokens before my turn.', 'RAD', 'RAD-USG', 'Bibhu Rout'],
  ['PATIENT', 5, 'My Token page is exactly what I need - position, people ahead, and the serving counter.', 'QUEUE_TRACKING', null, 'GM', 'GM-OPD', 'Mamta Panda'],
  ['PATIENT', 5, 'Clean design that works. The cardiology options were clear, and choosing follow-up was easy.', 'DEPARTMENT_SELECTION', null, 'CARD', 'CARD-FUP', 'Rina Mishra'],
  ['PATIENT', 1, 'Works well overall, but I found the navigation a little confusing on my first visit.', 'ACCESSIBILITY', 'Simplify navigation and add clearer labels.', 'OPD', 'OPD-TOK', 'Gopal Swain'],
  ['PATIENT', 5, 'Fast, simple, and the live board is a great addition to the waiting area.', 'LIVE_BOARD', null, 'BILL', 'BILL-INS', 'Lipi Senapati'],
  ['PATIENT', 5, 'No more long lines for the pharmacy. I picked a window and tracked my turn from the waiting area.', 'TOKEN_GENERATION', null, 'PHARM', 'PHARM-OP', 'Suchitra Kar'],
  ['PATIENT', 4, 'Straightforward and helpful. The directions to the department could be a little clearer.', 'DEPARTMENT_SELECTION', 'Add clearer directions to each department.', 'GM', 'GM-FUP', 'Priya Sahoo'],
  ['PATIENT', 1, 'The idea is great, but loading felt slow and the layout jumped around on my phone.', 'PERFORMANCE', 'Improve mobile performance and stability.', 'NEURO', 'NEURO-DIAG', 'Sourav Jena'],
  ['PATIENT', 2, 'My token position seemed to lag behind what was shown on the TV board.', 'QUEUE_TRACKING', 'Ensure token status matches the TV board in real time.', 'DERM', 'DERM-PROC', 'Deepa Nanda'],
  ['PATIENT', 5, 'Really easy to understand, even without asking staff for help.', 'GENERAL', null, 'ENT', 'ENT-AUD', 'Mamta Panda'],
  ['PATIENT', 4, 'Notifications about my turn were timely. A sound alert option would be a nice extra.', 'NOTIFICATIONS', 'Add an optional sound alert for your turn.', 'CARD', 'CARD-DIAG', 'Rakesh Patnaik'],
  ['PATIENT', 3, 'It worked once I found the right department. A better search or an A-Z list would help.', 'DEPARTMENT_SELECTION', 'Add a search or A-Z list of departments and services.', 'BILL', 'BILL-COUNTER', 'Sneha Das'],
  ['PATIENT', 5, 'Being able to check my position without staying in the waiting area is a real time-saver.', 'QUEUE_TRACKING', null, 'GM', 'GM-OPD', 'Anita Mohanty'],
  ['PATIENT', 4, 'The app is quick to load and the schedule view helps me plan. A reminder before visiting would be nice.', 'APPOINTMENTS', 'Send reminders before scheduled visits.', 'CARD', 'CARD-OPD', 'Rina Mishra'],
  ['PATIENT', 5, 'Simple menu, clear token, helpful live board. Everything I needed on one screen.', 'GENERAL', null, 'OPD', 'OPD-REG', 'Nikhil Tripathy'],
  ['PATIENT', 4, 'Works fine on my phone. Making the touch targets a bit bigger would help while walking.', 'MOBILE_EXPERIENCE', 'Increase touch target sizes for mobile.', 'PATH', 'PATH-SAMP', 'Gopal Swain'],
  ['PATIENT', 1, 'The wait estimate was close but not always exact. More accurate times would help me plan better.', 'WAIT_TIME', 'Improve ETA using real-time counter performance.', 'RAD', 'RAD-MRI', 'Bibhu Rout'],
  ['PATIENT', 2, 'The site would not reliably refresh on slower mobile data, and my status went stale.', 'PERFORMANCE', 'Improve offline/network handling.', 'DERM', 'DERM-OPD', 'Suchitra Kar'],
  ['STAFF', 5, 'The live queue gives our team a clear view of patients waiting at different counters. It reduces repeated questions about who is next.', 'STAFF_EXPERIENCE', null, 'GM', 'GM-OPD', 'Dr. Meera Nair'],
  ['STAFF', 4, 'Token management is easier than before. A dashboard showing peak hours and service times would help with planning.', 'STAFF_EXPERIENCE', 'Add a staff dashboard with peak hours and service-time stats.', 'OPD', 'OPD-REG', 'Counter Officer J'],
  ['STAFF', 5, 'Seeing live counter load helps us balance work across windows. Much less confusion on busy mornings.', 'LIVE_BOARD', null, 'PATH', 'PATH-SAMP', 'Priya Sahoo'],
  ['STAFF', 3, 'The queue console is helpful, but moving a patient to another service area should be simpler.', 'STAFF_EXPERIENCE', 'Allow transferring a token between counters or service areas.', 'EMER', 'EMER-TRI', 'Kunal Barik'],
  ['STAFF', 4, 'Calling the next token is a single tap. A quick search by token or patient name would speed up service.', 'STAFF_EXPERIENCE', 'Add search by token number, name, or department.', 'PATH', 'PATH-REP', 'Suchitra Kar'],
  ['STAFF', 5, 'Digital queue records make end-of-day reporting much easier than the old paper log.', 'STAFF_EXPERIENCE', null, 'CARD', 'CARD-DIAG', 'Dr. Meera Nair'],
  ['STAFF', 4, 'Queue visibility is great. Auto open/close counters would reduce manual effort during rush hour.', 'STAFF_EXPERIENCE', 'Allow quickly opening and closing counters from the console.', 'PHARM', 'PHARM-OP', 'Counter Officer J'],
  ['PATIENT', 5, 'Great improvement over queuing by hand - the counter called me exactly when ready.', 'TOKEN_GENERATION', null, 'ORTHO', 'ORTHO-OPD', 'Arun Behera'],
  ['PATIENT', 4, 'Live board is a nice touch in the waiting area. A cleaner counter legend would help.', 'LIVE_BOARD', 'Clarify counter names on the live board.', 'CARD', 'CARD-ECG', 'Priya Sahoo'],
  ['PATIENT', 3, 'It works, but there was a delay before my position showed after getting the token.', 'QUEUE_TRACKING', 'Show queue position immediately after issuing a token.', 'RAD', 'RAD-XRAY', 'Anita Mohanty'],
  ['PATIENT', 2, 'Fine when connectivity is good, but it felt slow to load the counters page once.', 'PERFORMANCE', 'Optimize assets for slower networks.', 'BILL', 'BILL-INS', 'Gopal Swain'],
  ['PATIENT', 5, 'Arrived, got my token, sat down, and the app told me when to move. Excellent.', 'QUEUE_TRACKING', null, 'GM', 'GM-FUP', 'Sneha Das'],
  ['PATIENT', 4, 'Language support in English is fine for me, but a local language option would help many patients.', 'ACCESSIBILITY', 'Add Hindi and Odia language options.', 'PEDS', 'PEDS-IMM', 'Mamta Panda'],
  ['PATIENT', 3, 'Easy enough, though the steps for first-time users could be explained a little better.', 'GENERAL', 'Add a short guided tour for first-time users.', 'OPD', 'OPD-TOK', 'Sourav Jena'],
  ['PATIENT', 5, 'The confirmation screen after getting my token is very reassuring and clear.', 'TOKEN_GENERATION', null, 'PATH', 'PATH-REP', 'Nikhil Tripathy'],
  ['PATIENT', 4, 'Notifications worked well. I would like an option to see my token history for the day.', 'QUEUE_TRACKING', 'Allow viewing your token history.', 'OPD', 'OPD-REG', 'Lipi Senapati'],
  ['PATIENT', 5, 'As a senior patient, the large text and clear steps made it easy to use on my own.', 'ACCESSIBILITY', null, 'GM', 'GM-OPD', 'Bibhu Rout'],
  ['PATIENT', 4, 'The board showing the current token is really helpful while waiting. Adding expected time would be a bonus.', 'LIVE_BOARD', 'Show estimated time on the live board.', 'ENT', 'ENT-OPD', 'Deepa Nanda'],
  ['PATIENT', 5, 'Quick token, clear instructions, and I was out much sooner than expected.', 'TOKEN_GENERATION', null, 'CARD', 'CARD-ECG', 'Rina Mishra'],
  ['PATIENT', 4, 'It is reliable and the design is pleasant. A bigger map to the department would help newcomers.', 'DEPARTMENT_SELECTION', 'Show a map or floor guide to service areas.', 'RAD', 'RAD-USG', 'Suchitra Kar'],
  ['PATIENT', 3, 'The idea is convenient, but I wished I could add my own notes or a companion name to the token.', 'GENERAL', 'Allow linking a companion to the token.', 'GM', 'GM-FUP', 'Priya Sahoo'],
  ['PATIENT', 5, 'No queues, no confusion - just a clear token and a live tracker. Highly recommend.', 'QUEUE_TRACKING', null, 'NEURO', 'NEURO-OPD', 'Anita Mohanty'],
  ['STAFF', 5, 'Patients ask how long until their turn far less often now that they can see the queue themselves.', 'STAFF_EXPERIENCE', null, 'ENT', 'ENT-OPD', 'Kunal Barik'],
  ['STAFF', 4, 'The interface is good, but I would like an alert when a queue is getting too long or overloaded.', 'NOTIFICATIONS', 'Alert staff when queue depth is too high.', 'EMER', 'EMER-OBS', 'Suchitra Kar'],
  ['STAFF', 5, 'Counter performance is easy to read. A quick open/close toggle on each counter would help a lot.', 'STAFF_EXPERIENCE', 'Add an open/close toggle per counter.', 'RAD', 'RAD-CT', 'Dr. Meera Nair'],
  ['STAFF', 4, 'We can finally see workload at a glance and plan breaks without leaving counters empty.', 'STAFF_EXPERIENCE', null, 'PATH', 'PATH-BB', 'Counter Officer J'],
  ['STAFF', 3, 'The dashboard shows useful numbers. Average waiting time and patients served per day would round it out.', 'STAFF_EXPERIENCE', 'Add daily stats: average wait, patients served, and peak hours.', 'OPD', 'OPD-REG', 'Kunal Barik'],
  ['PATIENT', 5, 'The whole hospital flow feels smoother now. Getting the token and knowing my place removed most of the stress.', 'QUEUE_TRACKING', null, 'GM', 'GM-OPD', 'Mamta Panda'],
  ['PATIENT', 4, 'Really convenient. I would like the option to cancel my token myself if I cannot stay.', 'QUEUE_TRACKING', 'Let patients cancel a token with confirmation.', 'ENT', 'ENT-AUD', 'Sourav Jena'],
  ['PATIENT', 3, 'The search and department list are useful, but finding the emergency department link took a moment.', 'EMERGENCY_HELP', 'Make the emergency department link more prominent.', 'BILL', 'BILL-COUNTER', 'Rina Mishra'],
  ['PATIENT', 2, 'The app showed my token correctly at first, but later the page stopped updating and I missed my turn.', 'NOTIFICATIONS', 'Make turn notifications more reliable and immediate.', 'PHARM', 'PHARM-OP', 'Gopal Swain'],
  ['PATIENT', 5, 'Very impressed. The steps are clear and I did not have to ask anyone for help.', 'GENERAL', null, 'OPD', 'OPD-REG', 'Suchitra Kar'],
  ['PATIENT', 4, 'Works well and looks professional. A short video or image guide for each service would be great.', 'SERVICE_INFORMATION', 'Add images or a guide for each service.', 'DERM', 'DERM-OPD', 'Deepa Nanda'],
  ['PATIENT', 3, 'Good system, but I wish the waiting time refreshed automatically instead of my having to reload.', 'WAIT_TIME', 'Auto-refresh waiting-time estimates.', 'CARD', 'CARD-DIAG', 'Bibhu Rout'],
  ['PATIENT', 5, 'As a parent, being able to track my child\u2019s OPD token from the caf\u00e9 was wonderful.', 'QUEUE_TRACKING', null, 'PEDS', 'PEDS-OPD', 'Priya Sahoo'],
  ['PATIENT', 4, 'Simple and clear. Adding expected wait time for the lab would help plan pick-ups.', 'WAIT_TIME', 'Show expected wait for lab results.', 'PATH', 'PATH-SAMP', 'Anita Mohanty'],
  ['PATIENT', 3, 'It is convenient, but I found the number of menu items a little overwhelming at first.', 'DEPARTMENT_SELECTION', 'Simplify the main menu and group related services.', 'NEURO', 'NEURO-OPD', 'Sneha Das'],
  ['PATIENT', 5, 'Excellent experience. The token was ready before I reached the counter, so I did not wait at all.', 'TOKEN_GENERATION', null, 'RAD', 'RAD-CT', 'Lipi Senapati'],
  ['PATIENT', 4, 'Very good overall. A dark mode option would be easier on the eyes in the evening.', 'MOBILE_EXPERIENCE', 'Add a dark mode.', 'GM', 'GM-FUP', 'Mamta Panda'],
  ['PATIENT', 2, 'The idea is nice, but the page took long to load on the hospital Wi-Fi and sometimes crashed.', 'PERFORMANCE', 'Improve loading time and stability on public Wi-Fi.', 'BILL', 'BILL-INS', 'Nikhil Tripathy'],
  ['PATIENT', 5, 'I really like being able to see the current token on the board. It made the wait feel shorter.', 'LIVE_BOARD', null, 'ENT', 'ENT-OPD', 'Rakesh Patnaik'],
  ['PATIENT', 4, 'Helpful and easy to use. I would love an option to view this in Hindi as well.', 'ACCESSIBILITY', 'Add a Hindi UI option.', 'OPD', 'OPD-TOK', 'Gopal Swain'],
  ['STAFF', 5, 'Being able to call tokens digitally instead of shouting across the room is a huge improvement for the floor.', 'TOKEN_GENERATION', null, 'RAD', 'RAD-XRAY', 'Priya Sahoo'],
  ['STAFF', 4, 'The console is clean and fast. An undo option for a mistaken call would be very useful.', 'STAFF_EXPERIENCE', 'Add an undo action for accidental token calls.', 'OPD', 'OPD-REG', 'Counter Officer J'],
  ['STAFF', 5, 'We can see exactly who is waiting and for how long. Great for managing the morning rush.', 'STAFF_EXPERIENCE', null, 'PATH', 'PATH-SAMP', 'Dr. Meera Nair'],
  ['STAFF', 4, 'The system is reliable. Reporting peak-hour usage would help us schedule staff better.', 'STAFF_EXPERIENCE', 'Add peak-hour usage reports.', 'CARD', 'CARD-OPD', 'Kunal Barik'],
  ['STAFF', 3, 'It works well, but occasionally two counters call the same number if we do not refresh. A lock would help.', 'STAFF_EXPERIENCE', 'Prevent two counters from calling the same token.', 'EMER', 'EMER-TRI', 'Suchitra Kar'],
  ['PATIENT', 5, 'From registration to billing, every queue was clear and easy to follow. Great system.', 'QUEUE_TRACKING', null, 'BILL', 'BILL-COUNTER', 'Sneha Das'],
  ['PATIENT', 4, 'Easy to use and the notifications came on time. A summary after my visit would be a nice extra.', 'GENERAL', 'Show a visit summary after completion.', 'GM', 'GM-OPD', 'Suchitra Kar'],
  ['PATIENT', 3, 'It works well on a good connection. On poor signal the page took a while to respond.', 'PERFORMANCE', 'Add a lightweight offline mode for basic info.', 'OPD', 'OPD-REG', 'Deepa Nanda'],
  ['PATIENT', 5, 'I appreciated how clearly the steps were shown. Even first-time visitors will manage easily.', 'TOKEN_GENERATION', null, 'PHARM', 'PHARM-OP', 'Rina Mishra'],
  ['PATIENT', 4, 'The counters were easy to find and the live board matched what I saw on my phone.', 'LIVE_BOARD', null, 'RAD', 'RAD-XRAY', 'Nikhil Tripathy'],
  ['PATIENT', 3, 'Helpful overall. It would be even better if the estimated wait time adjusted when a counter opened up.', 'WAIT_TIME', 'Recompute wait time when counters open or close.', 'CARD', 'CARD-FUP', 'Lipi Senapati'],
  ['PATIENT', 5, 'Short and sweet - it just works. I got my token and knew exactly when to return.', 'QUEUE_TRACKING', null, 'ENT', 'ENT-OPD', 'Bibhu Rout'],
  ['STAFF', 5, 'The live queue makes managing the department so much easier. Fewer phone calls asking where to go.', 'STAFF_EXPERIENCE', null, 'GM', 'GM-OPD', 'Dr. Meera Nair'],
  ['STAFF', 4, 'Great tool for staff. I would like bulk actions, like skipping or cancelling several at once.', 'STAFF_EXPERIENCE', 'Add bulk actions for tokens.', 'PATH', 'PATH-SAMP', 'Counter Officer J'],
  ['STAFF', 5, 'We can see the full picture of every counter, which helps us move staff to where it is busiest.', 'STAFF_EXPERIENCE', null, 'OPD', 'OPD-REG', 'Priya Sahoo'],
  ['STAFF', 3, 'The service is good, but the search could include token numbers typed with the department prefix.', 'STAFF_EXPERIENCE', 'Support searching by full or partial token number.', 'RAD', 'RAD-CT', 'Kunal Barik'],
  ['STAFF', 5, 'Very helpful for daily operations. I can finally plan the queues without constant guesswork.', 'STAFF_EXPERIENCE', null, 'CARD', 'CARD-OPD', 'Suchitra Kar'],
  ['STAFF', 4, 'Reliable and easy to train new staff on. A reset button for a stuck counter would be useful.', 'STAFF_EXPERIENCE', 'Add a counter reset/reopen action.', 'ENT', 'ENT-OPD', 'Dr. Meera Nair'],
  ['STAFF', 2, 'Occasionally the queue list froze and needed a refresh to show the latest token.', 'PERFORMANCE', 'Improve queue refresh reliability.', 'EMER', 'EMER-TRI', 'Counter Officer J'],
  ['STAFF', 5, 'Everything we need is in one place. Calling, holding, skipping and completing is very smooth.', 'STAFF_EXPERIENCE', null, 'PATH', 'PATH-REP', 'Dr. Meera Nair'],
  ['STAFF', 4, 'It has reduced the paperwork significantly. A printer-friendly summary would help at the counter.', 'STAFF_EXPERIENCE', 'Add printer-friendly token summaries.', 'OPD', 'OPD-REG', 'Kunal Barik'],
  ['STAFF', 3, 'The system helps, but handling emergency and priority patients alongside the regular queue needs improvement.', 'STAFF_EXPERIENCE', 'Add priority handling for emergency and senior patients.', 'EMER', 'EMER-OBS', 'Suchitra Kar'],
  ['STAFF', 5, 'My team adopted it quickly because it is intuitive. The live board removed a lot of confusion.', 'STAFF_EXPERIENCE', null, 'RAD', 'RAD-MRI', 'Priya Sahoo'],
  ['STAFF', 4, 'Very useful. A quick report of tokens served per hour would help me plan staffing.', 'STAFF_EXPERIENCE', 'Add hourly tokens-served reports.', 'GM', 'GM-OPD', 'Counter Officer J'],
  ['STAFF', 5, 'The dashboard is clear and the resolution of queue issues is much faster now.', 'STAFF_EXPERIENCE', null, 'PHARM', 'PHARM-OP', 'Dr. Meera Nair'],
];